tiles = [
	{ name="corner.png", symmetry="L" },
	{ name="cross.png", symmetry="I" },
	{ name="empty.png", symmetry="X" },
	{ name="line.png", symmetry="I" },
	{ name="t.png", symmetry="T" },
]

neighbors = [
	{ left="corner 1", right="empty" },
	{ left="corner", right="cross" },
	{ left="corner", right="cross 1" },
	{ left="corner", right="line" },
	{ left="corner 1", right="line 1" },
	{ left="corner", right="t 2" },
	{ left="corner", right="t 3" },
	{ left="corner", right="t" },
	{ left="corner 1", right="t 1" },
	{ left="corner 1", right="corner 3" },
	{ left="corner 1", right="corner" },
	{ left="corner", right="corner 1" },
	{ left="corner", right="corner 2" },
	{ left="cross", right="cross" },
	{ left="cross", right="cross 1" },
	{ left="cross 1", right="cross 1" },
	{ left="cross", right="line" },
	{ left="cross 1", right="line" },
	{ left="cross", right="t" },
	{ left="cross", right="t 3" },
	{ left="cross 1", right="t" },
	{ left="cross 1", right="t 3" },
	{ left="empty", right="empty" },
	{ left="empty", right="line 1" },
	{ left="empty", right="t 1" },
	{ left="line", right="line" },
	{ left="line 1", right="line 1" },
	{ left="line", right="t" },
	{ left="line 1", right="t 1" },
	{ left="line", right="t 3" },
	{ left="t 1", right="t 3" },
	{ left="t", right="t" },
	{ left="t 2", right="t" },
	{ left="t 1", right="t" },
	{ left="t 3", right="t 1" },
]
